name: CI Pipeline

on:
  push:
    branches:
      - master
      - staging
  pull_request:
    branches:
      - master
      - staging


jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests with pytest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          eval "$(poetry env activate)"
          poetry install --no-root
          python -m pytest

      - name: Run tests
        run: pytest